### ISSUE TITLE
Versioning and publishnig on crates.io

### ISSUE THREAD

**Issue by podhrmic** [coliasgroup/rust-seL4#1]
Hi @nspin !
Do you think you are getting close to start versioning the rust seL4 crates (e.g. 0.2, 0.3 etc) and publish the crates at `crates.io`?
That way we could start referencing the crates in more elegant way, rather than pinning the dependencies to a particular commit. Or are there still some significant uncertainties wrt. the crate design/API?

**Comment by nspin** [comment]
Hello!

I feel good about the design, but I'm hoping to receive more feedback from the community before starting to host these crates on https://crates.io. I agree that `git =` dependencies aren't the most pleasant to work with, and I'm hoping to reach that necessary level of confidence that the community is satisfied with the design soon!

**Comment by nspin** [comment]
I've considered hosting the crates at an alternative registry (one hosted at https://coliasgroup.com, containing just the crates in this project) in the meantime. That would make it easier to depend on them until they are properly hosted on https://crates.io.

Here are links to some of my experiments in this area:
- https://github.com/coliasgroup/rust-seL4/tree/main/hacking/other-tests/registry
- https://github.com/coliasgroup/rust-seL4/blob/main/hacking/nix/scope/registry.nix

**Comment by podhrmic** [comment]
That makes sense! For the time being we are happy with pinning to a specific commit, can update later as things stabilize.

**Comment by nspin** [comment]
In the meantime, leverage the `[workspace.dependencies]` feature of Cargo [1] can make dealing with git dependencies easier. I've updated https://github.com/coliasgroup/rust-seL4-sel4cp-demo to use this feature with https://github.com/coliasgroup/rust-seL4-sel4cp-demo/commit/0250aa314c9313aef1bb531cc4e545daa133a33d.

[1] https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table
